### ISSUE TITLE
my-metadata and search links fail on localhost, due to missing port number

### ISSUE THREAD

**Issue by dennisvang** [FAIRDataTeam/FAIRDataPoint-client#152]
When running the docker images for fdp 1.16 and fdp-client 1.17.0 (or 1.16.3) on `localhost`, the url `port` is not preserved in the links on the `my-metadata` page and the `search` page.

If the server listens on a non-default port, such as `8080`, the missing port number causes these links to fail.

For example,  the links on the page `http://localhost:8080/my-metadata` look like `http://localhost/catalog/<uuid4>`. Note the missing `:8080`.

![fdp-screenshot](https://github.com/user-attachments/assets/85f1b59a-15f0-44db-bb01-32188740b06d)

Docker compose file:

```yaml
services:
    fdp:
        image: fairdata/fairdatapoint:1.16
    fdp-client:
        image: fairdata/fairdatapoint-client:1.17
        ports:
         - 8080:80
        environment:
            - FDP_HOST=fdp
    mongo:
        image: mongo:4.0.12
```

### EDIT:

Looks like this issue belongs with the FDP backend instead of the client, judging from the `search` query response content

```json
[{"uri":"http://localhost/dataset/", ...}]
```
and `my-metadata` dashboard response

```json
[{"uri":"http://localhost/catalog/ec89411a-3a5e-4498-b742-418863a5e355","title":"my catalog", ...}]
```

**Comment by dennisvang** [comment]
Using `image: fairdata/fairdatapoint:1.17` with `ports: 80:80` I see the opposite, viz. the links do contain a port `:8080` even though the port should be `80`.

**Comment by dennisvang** [comment]
This applies to the current develop image (70acf75) in combination with the develop FDP ([75013ff]), where the "format" links don't work because they contain the fdp container port, as in http://localhost:8080/dataset/dataset-1?format=ttl, while the fdp is not exposed to the docker host.

![Image](https://github.com/user-attachments/assets/fc561630-43bf-46a9-838f-906d4369ab20)

compose.yml (showing only relevant part):

```yaml
services:
  fdp:
    image: fairdata/fairdatapoint:develop

  fdp-client:
    image: fairdata/fairdatapoint-client:develop
    ports:
      - "127.0.0.1:80:80"
    environment:
      FDP_HOST: fdp:8080
```

application.yml:

```yaml
instance:
  clientUrl: http://localhost

server:
  port: 8080
```

[75013ff]: https://github.com/FAIRDataTeam/FAIRDataPoint/commit/75013ffdf3b3fd7562f7baee133eb4a11fa07f70

**Comment by dennisvang** [comment]
This looks like a matter of improper configuration.

The problem disappears if we specify both `clientUrl` and `persistentUrl` for the FDP, for example:

```yaml
  fdp:
    ...
    environment:
      INSTANCE_CLIENTURL: http://localhost
      INSTANCE_PERSISTENTURL: http://localhost
    ...
```

Minimal compose file examples:
- [v1.16]
- [v1.17] 
- [v2.0 alpha]

[v1.16]: https://gist.github.com/dennisvang/2ff43e8203fbdfd5a25a6facf09b6c0a
[v1.17]: https://gist.github.com/dennisvang/f8f2f78bdacc7e8924cb22ceff1fb481
[v2.0 alpha]: https://gist.github.com/dennisvang/f7fb216cdb4fd36fe814af3185e29a32
