### ISSUE TITLE
blank settings page

### ISSUE THREAD

**Issue by dennisvang** [FAIRDataTeam/FAIRDataPoint-client#167]
*This is just some background for b5d6e43 by @MarekSuchanek*

Running the current `develop` version (e5940b3) from source on my local machine, with the FDP v2.0.0-alpha.1 backend in docker, we get a blank settings page:

![screenshot blank settings](https://github.com/user-attachments/assets/d14b7c0b-605e-461b-86b3-e3c6f17d9e0d)

The browser console shows the following error:

```none
[Vue warn]: Error in render: "TypeError: _vm.settingsData.repository is undefined"

found in

---> <Page> at src/components/Page/index.vue
       <FdpSettings> at src/views/FdpSettings/index.vue
         <App> at src/App.vue
           <Root>
```

<details>
<summary>Click to see setup details</summary>

```js
// public/config.js
window.config = {
  apiURL: 'http://localhost:8080',
}
```

```yaml
# compose.yml
name: fdpv2
services:
  fdp:
    image: fairdata/fairdatapoint:2.0.0-alpha.1
    ports:
      # must match the apiURL in fdp-client public/config.js
      - "127.0.0.1:8080:8080"
    environment:
      INSTANCE_INDEX: true
      # start fdp first, so that 8080 is taken and fdp-client will use 8081
      INSTANCE_CLIENTURL: http://localhost:8081
      INSTANCE_PERSISTENTURL: http://localhost:8081
      # fdp container port
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fdp
      JAVA_TOOL_OPTIONS: -Dspring.profiles.active=development
      SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: wget -q --spider http://localhost:8081 || exit 1
      start_interval: 3s
      start_period: 30s

  postgres:
    image: postgres
    healthcheck:
      test: pg_isready --dbname=fdp --username=fdp || exit 1
      start_interval: 3s
      start_period: 30s
    environment:
      POSTGRES_DB: fdp
      POSTGRES_USER: fdp
      POSTGRES_PASSWORD: fdp
```

</details>
