### ISSUE TITLE
Cannot add back an optional blank node when creating new metadata

### ISSUE THREAD

**Issue by kburger** [FAIRDataTeam/FAIRDataPoint-client#201]
Related to #198 and #200. When creating a new metadata instance, an optional blank node can now be removed. Trying to get it back is not possible using `v1.17.1-rc.3`.

Before, showing a red cross at "Temporal coverage::

![Image](https://github.com/user-attachments/assets/cff056c3-59c6-43fe-8857-2a3700fc0f98)

After, only showing the heading "Temporal coverage" and no plus button:

![Image](https://github.com/user-attachments/assets/5f485c31-79e5-4dcd-9af7-1da22078587e)

**Comment by dennisvang** [comment]
Hi @kburger thanks for the report. Unfortunately, I'm having trouble reproducing this.

Here's what I tried. Could you tell me if this reproduces the issue for you?

1. run this compose file:

   <details><summary>compose.117.yml</summary>
   <p>

   ```yaml
   name: fdp117
   services:
     mongo:
       image: "mongo:8.0"
       healthcheck:
         test: |
           [ $(mongosh --quiet --host localhost:27017 --eval "db.runCommand('ping').ok") = 1 ] || exit 1
         start_interval: 3s
         start_period: 30s

     fdp:
       image: "fairdata/fairdatapoint:1.17.4"
       environment:
         SERVER_PORT: 8080
         INSTANCE_CLIENTURL: http://localhost
         INSTANCE_PERSISTENTURL: http://localhost
       depends_on:
         mongo:
           condition: service_healthy
       healthcheck:
         test: wget -q --spider http://localhost:8080 || exit 1
         start_interval: 3s
         start_period: 30s

     fdp-client:
       image: "fairdata/fairdatapoint-client:1.17.1-rc.3"
       ports:
         - "127.0.0.1:80:80"
       environment:
         - FDP_HOST=fdp:8080
       depends_on:
         fdp:
           condition: service_healthy
   ```

   </p>
   </details> 

2. log in as admin
3. modify the `Resource` schema so that `dct:publisher` has `sh:minCount 0 ;` then "Save and release"
4. visit http://localhost/create-catalog
5. click `x` to remove the publisher

In my case this works:

![Image](https://github.com/user-attachments/assets/e80f481e-9516-4444-a049-3339cb7cf8cf)

![Image](https://github.com/user-attachments/assets/9f7eb82d-e497-4c64-ab49-cd7646043ed9)
